### ISSUE TITLE
Reconfigure, redeploy

### ISSUE THREAD

**Issue by jmn** [mozilla/mattermost-heroku#4]
Hi, Awesome buildpack.

I'm a bit puzzled with regards to reconfiguring redeploying this when using the one click deploy and the documentation states "Rebuilding - Use the deploy menu on the Heroku dashboard to trigger manual deploys." Unfortunately I don't think this is possible. Please correct me if I'm wrong but it looks to me as if the only way to trigger a Heroku deploy is via git push. 

And so the way then to rebuild is (I think), do:
```
heroku git:clone --app YOURAPPNAME && cd YOURAPPNAME
git remote add origin https://github.com/mozilla/mattermost-heroku
git pull origin master
git push heroku master
```
If You find this to be correct, perhaps include it in the README.MD?

**Comment by cadecairos** [comment]
Hi @jmn, apologies for the delayed response, I just saw this issue.

It seems like the deploy option is only available if you're connected to a github repo - a bit of an oversight on my part. 

Simply pushing isn't going to trigger a build because Heroku won't detect any changes. I'd suggest using the platform API's build enpoint to [create a new build](https://devcenter.heroku.com/articles/build-and-release-using-the-api#creating-builds).

This can be done manually or via CI (like TravisCI or a self hosted Jenkins server)

```bash
curl -n -X POST https://api.heroku.com/apps/$YOUR_APP/builds \
-d '{"source_blob": {"url":"$PROJECT_TAR_FILE", "version": "$COMMIT_HASH"}}' \
-H 'Accept: application/vnd.heroku+json; version=3' \
-H "Content-Type: application/json"
```

I'll add this information to the README

**Comment by cadecairos** [comment]
Fixed in https://github.com/mozilla/mattermost-heroku/commit/eb68d6f62038f673fd8904cb8c9d80b3cb9a2fb2
